# This file is generated by gyp; do not edit.

export builddir_name ?= ./out
.PHONY: all
all:
	$(MAKE) cheb matrix sort sys err complex vector ieeeutils utils combination multiset blas block test permutation rng specfunc randist gsl
